export const cities: any = {
  "Altos": "altos",
  "Asunción": "asuncion",
  "Caacupé": "caacupe",
  "Caazapá": "caazapa",
  "Ciudad del Este": "ciudad_del_este",
  "El Dorado": "el_dorado",
  "Emboscada": "emboscada",
  "Itauguá": "itagua",
  "María Auxiliadora": "maria_auxiliadora",
  "Ñemby": "nemby",
  "Paraguarí": "paraguari",
  "Pilar": "pilar",
  "San Bernardino": "san_bernardino",
  "San Ignacio": "san_ignacio",
  "Santa Rita": "santa_rita",
  "Santa Rosa": "santa_rosa",
  "Villa Florida": "villa_florida",
  "Villeta": "villeta",
  "Ybycuí": "ybycui",
};